version: '3'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8888:8888
      - 5555:5555
    volumes:
      - ../logs/api:/usr/src/app/api/logs
    networks:
      - u2u-nw
    logging:
      driver: "json-file"
      options:
        max-size: 300m
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
  redis:
    image: redis
    command: >
      --requirepass apimarketplace
    networks:
      - u2u-nw
    volumes:
      - redis-data:/data
networks:
  u2u-nw:
    external: false
    name: u2u-nw
volumes:
  redis-data:
