# Use Node.js as the base image
FROM node:20.2.0-alpine3.18

RUN apk update && apk add --no-cache python3 make g++ xdg-utils

ADD . /app

# Define working directory
WORKDIR /app

# Install the Nest CLI globally
RUN yarn global add @nestjs/cli

# Install project dependencies
RUN yarn install

RUN npx prisma generate
RUN npx prisma generate --schema=./prisma-second/schema.prisma
RUN yarn add --platform=linuxmusl --arch=arm64v8 sharp
CMD yarn start:dev 

# ENTRYPOINT ["tail", "-f", "/dev/null"]
